GET http://localhost:8080/api/products/mocking-products

### 
POST http://localhost:8080/api/products/
Content-Type: application/json

{
   "status": true,
    "title": "",
    "description": "auriculares",
    "price": "",
    "thumbnails": [],
    "code": "auricu12",
    "stock": "1",
    "category": "electro"
}

### 
POST http://localhost:8080/api/products/
Content-Type: application/json

{
    "status": true,
    "title": "teclado",
    "description": "teclado steel",
    "price": "2111",
    "thumbnails": [],
    "code": "tecla23",
    "stock": "5",
    "category": "electro"
}
